# Generated by Django 5.0.4 on 2024-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_autor_nome_alter_autor_sobrenome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='livro_valor',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=4),
        ),
    ]
